apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: dataproduct-topics
  namespace: aura
  labels:
    team: aura
spec:
  image: "{{ image }}"
  schedule: "13 4 * * *"

  {{#if kafka_pool }}
  kafka:
    pool: "{{ kafka_pool }}"
  {{/if}}

  {{#if kafka_brokers }}
  env:
    - name: ONPREM
      value: "true"
    - name: KAFKA_BROKERS
      value: "{{ kafka_brokers }}"
    - name: LINKERD_AWAIT_DISABLED
      value: "no linkerd onprem!"
  {{/if}}

  {{#if kafka_serviceuser_vault_path }}
  vault:
    enabled: true
    paths:
      - format: env
        kvPath: "{{ kafka_serviceuser_vault_path }}"
        mountPath: /var/run/secrets/nais.io/kafka_serviceuser
  {{/if}}
