name: Create docker image

on:
  push:

env:
  "IMAGE": "ghcr.io/${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: "Set image version"
      id: set-image-tag
      run: |
        export IMAGE_TAG="$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "::set-output name=image::${IMAGE}:${IMAGE_TAG}"
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and possibly push
      env:
        EARTHLY_PUSH: "${{ github.ref == 'refs/heads/main' }}"
      run: |
        ./earthlyw config global.local_registry_host 'tcp://127.0.0.1:8371'
        ./earthlyw --ci --build-arg IMAGE_TAG --build-arg IMAGE +docker
    outputs:
      image: "${{ steps.set-image-tag.outputs.image }}"
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        cluster:
          - dev-gcp
          - dev-fss
          - prod-gcp
          - prod-fss
    steps:
      - uses: "actions/checkout@v2"
      - uses: nais/deploy/actions/deploy@v1
        name: Deploy to ${{ matrix.cluster }}
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais/job.yaml
          VARS: nais/vars-${{ matrix.cluster }}.yaml
          VAR: image=${{ needs.build.outputs.image }},gcp_sa_json_base64=${{ secrets.GCP_SA_JSON_BASE64 }},pool_name=${{ matrix.cluster}}